---
- name: Install MariaDB
  apt: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
  tags:
    - mysql

- name: Install MySQLdb Python package
  apt: pkg=python-mysqldb state=present
  tags:
    - mysql

- name: Restart MariaDB MySQL Server
  service:
    name: mysql
    state: restarted
    enabled: true
  tags:
    - mysql

- name: Set root user password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags:
    - mysql

- name: Copy .my.cnf file with root password credentials.
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600
  tags:
    - mysql

- name: Delete anonymous MySQL server users
  mysql_user:
    user: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags:
    - mysql

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  tags:
    - mysql
